package com.example.model

enum class GameCategory(val title: String) {
    ALL("All Games"),
    ACTION("Action"),
    ARCADE("Arcade"),
    PUZZLE("Puzzle"),
    RACING("Racing"),
    SPORTS("Sports"),
    STRATEGY("Strategy"),
    BRAIN("Brain"),
    CASUAL("Casual"),
    NEW("New Games")
}

enum class GameType {
    TIC_TAC_TOE,
    ROCK_PAPER_SCISSORS,
    SNAKE,
    MEMORY_MATCH,
    NUMBER_GUESS,
    TAP_CHALLENGE,
    COLOR_MATCH,
    QUICK_MATH,
    WORD_GUESS,
    CONNECT_FOUR,
    GAME_2048,
    MINESWEEPER,
    BRICK_BREAKER,
    FLAPPY_BIRD,
    ENDLESS_RUNNER,
    MINI_RACING,
    CAR_DODGE,
    BASKETBALL_SHOT,
    FOOTBALL_PENALTY,
    CRICKET_BATTING,
    CRICKET_TARGET,
    TABLE_TENNIS,
    AIR_HOCKEY,
    BOWLING,
    ARCHERY,
    KNIFE_TARGET,
    BUBBLE_SHOOTER,
    BLOCK_PUZZLE,
    SLIDING_PUZZLE,
    SUDOKU,
    CROSSWORD,
    WORD_SCRAMBLE,
    HANGMAN,
    MATH_CHALLENGE,
    ADDITION_CHALLENGE,
    MULTIPLICATION_CHALLENGE,
    MEMORY_NUMBERS,
    REACTION_TEST,
    SPEED_TAP,
    TAP_THE_TARGET,
    CATCH_THE_BALL,
    AVOID_THE_BOMB,
    JUMP_GAME,
    PLATFORM_JUMPER,
    SPACE_SHOOTER,
    ALIEN_SHOOTER,
    ASTEROID_DODGE,
    ZOMBIE_ESCAPE,
    TOWER_DEFENSE,
    MAZE_ESCAPE,
    TREASURE_HUNT,
    COIN_COLLECTOR,
    COLOR_SWITCH,
    MATCH_3,
    FRUIT_SLICE,
    BALLOON_POP,
    BUBBLE_POP,
    STACK_BLOCKS,
    TOWER_STACK,
    KNIFE_THROW,
    FISHING,
    CAR_PARKING,
    TRAFFIC_DODGE,
    BIKE_RACING,
    BOAT_RACING,
    PLANE_DODGE,
    SPACE_RUNNER,
    BASKETBALL_DUNK,
    FOOTBALL_GOAL,
    CRICKET_SIX,
    CRICKET_BOWLING,
    TENNIS_HIT,
    GOLF_MINI,
    BOXING_TAP,
    WRESTLING_TAP,
    CHESS_PUZZLE,
    CHECKERS,
    WORD_SEARCH,
    PATTERN_MATCH,
    FIND_THE_DIFFERENCE,
    FIND_THE_ODD_ONE,
    MEMORY_CARDS,
    SIMON_SAYS,
    COLOR_MEMORY,
    SHAPE_MATCH,
    QUICK_REACTION,
    BRAIN_TEST,
    LOGIC_PUZZLE,
    IQ_CHALLENGE,
    NUMBER_PUZZLE,
    SEQUENCE_PUZZLE,
    EMOJI_GUESS,
    FLAG_GUESS,
    ANIMAL_GUESS,
    FOOD_GUESS,
    MOVIE_GUESS,
    GENERAL_KNOWLEDGE_QUIZ,
    SPORTS_QUIZ,
    GEOGRAPHY_QUIZ,
    RAPID_QUIZ,
    ENDLESS_TAP,
    LUCKY_NUMBER
}

data class Game(
    val id: Int,
    val number: String,
    val name: String,
    val category: GameCategory,
    val description: String,
    val icon: String,
    val gameType: GameType
)

data class Achievement(
    val id: String,
    val title: String,
    val description: String,
    val icon: String,
    val isUnlocked: Boolean = false
)

data class PlayerStats(
    val gamesPlayed: Int,
    val gamesWon: Int,
    val bestScore: Int,
    val favoriteCount: Int,
    val achievements: List<Achievement>
)
